FROM {{.stack.baseimage}} as compile

USER root

RUN dnf --disableplugin=subscription-manager install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm \
  && dnf --disableplugin=subscription-manager install -y unzip curl ca-certificates wget xmlstarlet \
  && dnf --disableplugin=subscription-manager update -y; dnf --disableplugin=subscription-manager clean all

RUN  groupadd --gid 1000 java_group \
  && useradd --uid 1000 --gid java_group --shell /bin/bash --create-home java_user \
  && mkdir -p /mvn/repository \
  && chown -R java_user:java_group /mvn \
  && mkdir -p /opt/ol \
  && chown -R java_user:java_group /opt \
  && mkdir -p /config \
  && mkdir -p /licenses \
  && mkdir -p /project \
  && mkdir -p /usr/share/maven \
  && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn \
  && chown -R java_user:java_group /licenses /config /project /opt/java/openjdk /usr/share/maven

USER java_user

#
# Install maven
#
# This section based upon:
#   https://github.com/kabanero-io/collections/blob/master/docker/Dockerfile-maven
#

ARG MAVEN_VERSION=3.6.3
ARG USER_HOME_DIR="/root"
ARG SHA=c35a1803a6e70a126e80b2b3ae33eed961f83ed74d18fcd16909b2d44d7dada3203f1ffe726c17ef8dcca2dcaa9fca676987befeadc9b9f759967a8cb77181c0
ARG BASE_URL=https://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/

RUN mkdir -p /usr/share/maven/ref \
  && curl -fsSL -o /tmp/apache-maven.tar.gz ${BASE_URL}/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
  && echo "${SHA}  /tmp/apache-maven.tar.gz" | sha512sum -c - \
  && tar -xzf /tmp/apache-maven.tar.gz -C /usr/share/maven --strip-components=1 \
  && rm -f /tmp/apache-maven.tar.gz

ENV MAVEN_HOME /usr/share/maven
ENV MAVEN_CONFIG "$USER_HOME_DIR/.m2"

COPY ./LICENSE /licenses/
COPY --chown=java_user:java_group ./project /project
COPY --chown=java_user:java_group ./config /config

RUN  /project/util/check_version build

WORKDIR /project/

RUN mkdir -p /mvn/repository
# Let's see the command we're hiding within the next line
RUN mvn -e help:evaluate -Dexpression=maven.version -DforceStdout
RUN mvn -B -Dmaven.repo.local=/mvn/repository -N io.takari:maven:wrapper -Dmaven=$(mvn help:evaluate -Dexpression=maven.version -q -DforceStdout)
RUN mvn -B -Pstack-image-package -Dmaven.repo.local=/mvn/repository liberty:install-server install dependency:go-offline
RUN chmod -R 777 /opt/ol 


WORKDIR /project/user-app

ENV APPSODY_MOUNTS="~/.m2/repository:/mvn/repository;.:/project/user-app"

ENV APPSODY_USER_RUN_AS_LOCAL=true

# Allow validate to distinguish build via APPSODY_DEV_MODE
ENV APPSODY_PREP="/project/run-stack.sh prep"

ENV APPSODY_RUN="/project/run-stack.sh run"

ENV APPSODY_DEBUG="/project/run-stack.sh debug"

ENV APPSODY_TEST="/project/run-stack.sh test"

ENV PORT=9080

EXPOSE 9080
EXPOSE 9443
EXPOSE 7777
